src/slave/src/org/drftpd/slave/Slave.java
The former code tried to delete the parent directory of a file when this one was empty. But did not check if the parent dir was still existing, throwing an Exception.
=> Try to deal with parallel deletion of files on slaves

src/master/src/org/drftpd/usermanager/AbstractUserManager.java
supporting pipes in the botname (that shouldn't be allowed, but isn't checked in the configuration). The commit also includes reformatting, mostly eclipse own stuff.
=> Use a regular expression to validate user idents

src/plugins/org.drftpd.protocol.zipscript.mp3.slave/src/org/drftpd/protocol/zipscript/mp3/slave/MP3Parser.java
Close id3parser since we're done with it
=> Update MP3Parser to close ID3Parser

src/slave/src/org/drftpd/bootstrap/URLBootStrap.java
Fix: IOException cannot be resolved to a type.
I forgot to add the import in #104
=> Fix: IOException cannot be resolved to a type

src/common/src/org/drftpd/util/PortRangeTest.java, src/plugins/org.drftpd.commands.autonuke/src/org/drftpd/commands/autonuke/DirsToCheck.java, src/plugins/org.drftpd.commands.config.hooks/src/org/drftpd/commands/config/hooks/DefaultConfigPreHook.java, src/plugins/org.drftpd.commands.imdb/src/org/drftpd/commands/imdb/event/IMDBEvent.java, src/plugins/org.drftpd.commands.sections/src/org/drftpd/commands/sections/Sections.java, src/plugins/org.drftpd.commands.tvmaze/src/org/drftpd/commands/tvmaze/TvMaze.java, src/plugins/org.drftpd.plugins.archive/src/org/drftpd/plugins/archive/archivetypes/MoveReleaseOffMultipleSlavesToSpecificSlaves.java, src/plugins/org.drftpd.plugins.archive/src/org/drftpd/plugins/archive/archivetypes/MoveReleaseOffSlavesToMostFreeSlaves.java, src/plugins/org.drftpd.plugins.linkmanager.latestdir/src/org/drftpd/plugins/linkmanager/types/latestdir/LatestDir.java, src/plugins/org.drftpd.plugins.linkmanager.latestdir/src/org/drftpd/plugins/linkmanager/types/latestdir/LatestDirManager.java, src/plugins/org.drftpd.plugins.prebw/src/org/drftpd/plugins/prebw/announce/PREBWAnnouncer.java, src/plugins/org.drftpd.plugins.sitebot.announce.pre/src/org/drftpd/plugins/sitebot/announce/pre/PreAnnouncer.java, src/plugins/org.drftpd.plugins.sitebot.plugins.dailystats/src/org/drftpd/plugins/sitebot/plugins/dailystats/DailyStats.java, src/plugins/org.drftpd.protocol.mediainfo.common/src/org/drftpd/protocol/mediainfo/common/MediaInfo.java, src/plugins/org.drftpd.slave.diskselection.filter/src/org/drftpd/slave/diskselection/filter/MinfreespaceFilter.java, src/plugins/org.drftpd.slaveselection.filter/src/org/drftpd/slaveselection/filter/SlaveSelectionManager.java, src/tools/org/drftpd/tools/installer/Wrapper.java, src/tools/org/drftpd/tools/installer/console/LogWindow.java, src/tools/org/drftpd/tools/installer/swing/LogWindow.java
Cleanup unused imports and remove unused hashmap in mediainfo
=> Cleanup unused imports and remove unused hashmap in mediainfo

src/master/src/org/drftpd/vfs/DirectoryHandle.java, src/plugins/org.drftpd.commands.dir/src/org/drftpd/commands/dir/Dir.java
- Bugfix to not assume we sent a relative path if we are in root
- Add a debug logger to show the actual permission denied error, which helps in troubleshooting
=> Bugfix to not assume we sent a relative path if we are in root

src/plugins/org.drftpd.commands.speedtest.net/src/org/drftpd/commands/speedtest/net/SpeedTestUtils.java, src/plugins/org.drftpd.commands.tvmaze/src/org/drftpd/commands/tvmaze/TvMazeParser.java, src/plugins/org.drftpd.commands.tvmaze/src/org/drftpd/commands/tvmaze/TvMazeUtils.java
JsonParser constructor has been deprecated for a static method
=> JsonParser constructor has been deprecated

src/core/master/src/main/resources/master/config/commands/ftp/core.conf
=> Allow IDNT command before authentication

src/plugins/tvmaze/src/main/resources/master/config/themes/ftp/tvmaze.theme.default
=> Remove unnecessary \n as the printOutput in bot/ftp already handle this

src/core/master/pom.xml, src/plugins/tvmaze/src/main/java/org/drftpd/tvmaze/master/TvMazeConfig.java, src/plugins/tvmaze/src/main/java/org/drftpd/tvmaze/master/TvMazeUtils.java, src/plugins/tvmaze/src/main/resources/master/config/themes/ftp/tvmaze.list.theme.default
=> Remove joda.time dependency and use java.time

src/core/master/src/main/java/org/drftpd/master/commands/login/LoginHandler.java, src/core/master/src/main/java/org/drftpd/master/commands/usermanagement/GroupManagementHandler.java, src/core/master/src/main/java/org/drftpd/master/commands/usermanagement/UserManagementHandler.java, src/core/master/src/main/java/org/drftpd/master/network/BaseFtpConnection.java, src/core/master/src/main/java/org/drftpd/master/usermanager/AbstractGroup.java, src/core/master/src/main/java/org/drftpd/master/usermanager/AbstractUser.java
=> Implement a way for users to kill their ghosts

src/core/master/src/main/java/org/drftpd/master/config/ConfigManager.java, src/plugins/dupecheck/src/main/java/org/drftpd/dupecheck/master/DupeCheckExtendedPermissions.java, src/plugins/dupecheck/src/main/java/org/drftpd/dupecheck/master/DupeCheckHooks.java
Implement more log lines so we can see what breaks or not
=> Add missing DupeCheck permission extension (fixes #177)

src/core/master/src/main/java/org/drftpd/master/commands/CommandInterface.java, src/core/master/src/main/java/org/drftpd/master/commands/usermanagement/notes/NotesPostHook.java, src/plugins/archive/src/main/java/org/drftpd/archive/master/commands/ArchiveCommandHandler.java, src/plugins/zipscript/zipscript-master/src/main/java/org/drftpd/zipscript/master/flac/hooks/ZipscriptFlacPostHook.java, src/plugins/zipscript/zipscript-master/src/main/java/org/drftpd/zipscript/master/mp3/hooks/ZipscriptMP3PostHook.java, src/plugins/zipscript/zipscript-master/src/main/java/org/drftpd/zipscript/master/sfv/hooks/ZipscriptPostHook.java, src/plugins/zipscript/zipscript-master/src/main/java/org/drftpd/zipscript/master/zip/hooks/ZipscriptZipPostHook.java
Inject command manager through constructor to prevent NPE
=> Inject command manager through constructor to prevent NPE

src/core/master/src/main/java/org/drftpd/master/commands/usermanagement/UserManagementHandler.java, src/core/master/src/main/java/org/drftpd/master/network/BaseFtpConnection.java, src/core/master/src/main/java/org/drftpd/master/usermanager/AbstractUserManager.java
=> Fix a race condition with renuser

.gitignore, src/plugins/autofreespace/src/main/java/org/drftpd/autofreespace/master/AutoFreeSpaceSettings.java, src/plugins/mirror/src/main/java/org/drftpd/mirror/master/MirrorSettings.java
* Fix code trying to load slave with empty name #207 
* Fix excludedSlaves not being loaded correctly in MirrorSettings #208 
* Fix MirrorSettings incrementing twice in the same loop causing entries to be skipped #206 
Closes: #206 #207 #208
=> AutoFreeSpace and MirrorSettings fixes

src/core/common/src/main/java/org/drftpd/common/util/ConfigLoader.java, src/core/common/src/main/java/org/drftpd/common/util/HostMaskCollection.java, src/core/master/src/main/java/org/drftpd/master/Master.java, src/core/master/src/main/java/org/drftpd/master/commands/login/LoginHandler.java, src/core/master/src/main/java/org/drftpd/master/network/BaseFtpConnection.java
=> Do ident earlier

src/core/common/src/main/java/org/drftpd/common/util/ConfigLoader.java, src/core/master/src/main/java/org/drftpd/master/commands/newhandler/New.java
=> Agecomparator contract violation

docs/ssl.txt, src/core/common/pom.xml, src/core/common/src/main/java/org/drftpd/common/exceptions/SSLServiceException.java, src/core/common/src/main/java/org/drftpd/common/network/SSLService.java, src/core/common/src/main/java/org/drftpd/common/util/PropertyHelper.java, src/core/master/pom.xml, src/core/master/src/main/java/org/drftpd/master/GlobalContext.java, src/core/master/src/main/java/org/drftpd/master/slavemanagement/SlaveManager.java, src/core/master/src/main/resources/master/config/master.conf.dist, src/core/master/src/test/java/org/drftpd/master/tests/DummySlaveManager.java, src/core/slave/pom.xml, src/core/slave/src/main/java/org/drftpd/slave/Slave.java, src/core/slave/src/main/resources/slave/config/slave.conf.dist, src/plugins/archive/src/test/java/org.drftpd.archive.master/MoveReleaseOffMultipleSlavesToSpecificSlavesTest.java
The master<->client and client<->connections(Passive/Active) will follow next.
=> Change master<->slave ssl/tls setup options

src/core/master/src/main/java/org/drftpd/master/GlobalContext.java, src/core/master/src/main/java/org/drftpd/master/indexation/AdvancedSearchParams.java, src/plugins/find/src/main/java/org/drftpd/find/master/Find.java, src/plugins/find/src/main/java/org/drftpd/find/master/FindSettings.java, src/plugins/find/src/main/java/org/drftpd/find/master/FindUtils.java, src/plugins/find/src/main/java/org/drftpd/find/master/Search.java, src/plugins/find/src/main/java/org/drftpd/find/master/action/ActionInterface.java, src/plugins/find/src/main/java/org/drftpd/find/master/flac/FlacOption.java, src/plugins/find/src/main/java/org/drftpd/find/master/mp3/MP3Option.java, src/plugins/find/src/main/java/org/drftpd/find/master/option/AgeOption.java, src/plugins/find/src/main/java/org/drftpd/find/master/option/LimitOption.java, src/plugins/find/src/main/java/org/drftpd/find/master/option/NameOption.java, src/plugins/find/src/main/java/org/drftpd/find/master/option/OptionInterface.java, src/plugins/find/src/main/java/org/drftpd/find/master/option/QuietOption.java, src/plugins/find/src/main/java/org/drftpd/find/master/option/SectionOption.java, src/plugins/find/src/main/java/org/drftpd/find/master/option/SizeOption.java, src/plugins/find/src/main/java/org/drftpd/find/master/option/SlaveOption.java, src/plugins/find/src/main/java/org/drftpd/find/master/option/SortOption.java, src/plugins/find/src/main/java/org/drftpd/find/master/option/UserOption.java, src/plugins/find/src/main/java/org/drftpd/find/master/zipscript/ZipscriptOption.java, src/plugins/find/src/main/resources/master/config/commands/ftp/find.conf, src/plugins/find/src/main/resources/master/config/commands/irc/find.conf, src/plugins/imdb/imdb-master/src/main/java/org/drftpd/imdb/master/find/IMDBOption.java, src/plugins/tvmaze/src/main/java/org/drftpd/tvmaze/master/find/TvMazeOption.java
=> Update find plugin from JPF to Reflections

src/plugins/autofreespace/src/main/java/org/drftpd/autofreespace/master/AutoFreeSpace.java, src/plugins/autofreespace/src/main/java/org/drftpd/autofreespace/master/AutoFreeSpaceSettings.java, src/plugins/autofreespace/src/main/resources/master/config/plugins/autofreespace.conf.dist
- Add a max iterations per slave config variable to limit the amount of iterations in a single run per slave
- Add more logging and logic to the runs
- MrCleanIt class now has a boolean whether it is already running or not and deny a second run
=> Try to improve the AutoFreeSpace plugin in various ways (Fix #236)

pom.xml, src/core/common/pom.xml, src/core/master/pom.xml, src/core/slave/pom.xml, src/plugins/speedtest-net/speedtest-net-slave/pom.xml
This also includes dependabot's PR #278
=> Update dependencies to latest api compatible versions

src/core/master/pom.xml, src/core/master/src/main/java/org/drftpd/master/usermanager/encryptedjavabeans/EncryptedBeanUser.java, src/core/master/src/main/java/org/drftpd/master/usermanager/encryptedjavabeans/EncryptedBeanUserManager.java, src/core/master/src/test/java/org/drftpd/master/master/usermanager/EncryptedBeanUserTest.java, src/core/master/src/test/java/org/drftpd/master/tests/DummyEncryptedBeanUserManager.java
Add argon2 password hashing according to issue #183
Add glftpd password hashing to enable migration of user data from glftpd
=> Add argon2 and glftpd password hashing

.github/dependabot.yml, .github/workflows/build-and-push-docker-images.yml, .github/workflows/maven-build-upload-dependency-graph-artifacts.yml, Dockerfile, README.md
To push Docker images to GitHub Container Registry (ghcr.io):
-grant repository write access to GitHub packages
To push Docker images to Docker Hub (docker.io):
-uncomment Docker Hub related lines in build-and-push-docker-images.yml
-configure env.DOCKERHUB_USERNAME and secrets.DOCKERHUB_ACCESSTOKEN
=> Add workflows for Docker, Dependabot and Dependency graph

src/core/common/src/test/java/org/drftpd/common/HostMaskTest.java, src/core/master/src/test/java/org/drftpd/master/common/util/HostMaskTest.java
Add more tests to validate https://github.com/drftpd-ng/drftpd/issues/290
=> HostMaskTest more wildcard positions

src/core/master/src/main/java/org/drftpd/master/commands/usermanagement/GroupManagementHandler.java
`if (requestedUser == null)` would be dead code as we'd except while trying to put it in env
=> move variable to post null-check

src/core/slave/src/main/java/org/drftpd/slave/protocol/BasicHandler.java
This could be interesting information, but is not justified to spam log in "production"
=> change message to debug loglevel

src/core/master/src/main/java/org/drftpd/master/network/RemoteTransfer.java, src/core/slave/src/main/java/org/drftpd/slave/network/Transfer.java
=> We want the slave to acknowledge abort with a timeout to not wait infinitely

Dockerfile, README.md, src/core/master/src/main/resources/master/master.bat, src/core/master/src/main/resources/master/master.sh, src/core/slave/src/main/resources/slave/slave.bat, src/core/slave/src/main/resources/slave/slave.sh
ZGC reporting was a bit inconsistent with memory usage and caused pauses in the master process, timing out ftp session. Switching back to G1GC.
=> Switch back to G1GC. Update systemd templates

src/core/master/src/main/resources/master/config/encryptedbeanuser.conf.dist
Document glftpd and argon2 password hashing options
=> Update valid options in encryptedbeanuser.conf

src/plugins/imdb/imdb-master/src/main/java/org/drftpd/imdb/master/IMDBParser.java
This should be okay for the new layout from imdb.
If anyone can, give it a try before merge.
=> Updated IMDBParser to the new layout
